home/forms.py
# coding:utf-8
from urllib.request import Request, urlopen
from flask import json
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, ValidationError
from common.configs import VAPTCHA_ID, VAPTCHA_SECRET_KEY

class VaptchaForm(FlaskForm):
    api_url = 'http://api.vaptcha.com/v2/validate'
    api_id  = VAPTCHA_ID,
    api_key = VAPTCHA_SECRET_KEY,

    vaptcha_token = StringField()

    def validate_vaptcha_token(self,field):
        uri = 'id={}&secretkey={}&token={}'.format(VAPTCHA_ID,VAPTCHA_SECRET_KEY,field.data)
        uri = bytes(uri,encoding='utf-8')

        request3 = Request(self.api_url, data=uri)
        response = urlopen(request3)
        html = response.read().decode('utf-8')
        jsond = json.loads(html)

        if jsond.get('success') != 1: raise ValidationError('请先进行人机验证')


class LoginForm(VaptchaForm):

    username = StringField(
        label='帐户',
        description='帐户',
        validators=[
            DataRequired('帐户不能为空!')
        ],
        render_kw={
            'class':'layui-input',
            'placeholder':'请输入帐户',
            'required':'required',
            'lay-verify':'required',
            'autocomplete':'off',
        }
    )

    password = PasswordField(
        label='密码',
        description='密码',
        validators=[
            DataRequired('密码不能为空!')
        ],
        render_kw={
            'class':'layui-input',
            'placeholder':'请输入密码',
            'required':'required',
            'lay-verify':'required',
            'autocomplete':'off',
        }
    )

    submit = SubmitField(
        '立即登录',
        render_kw={
            'class': 'layui-btn',
            'lay-filter':'*',
            'lay-submit':None
        }
    )

class ReviewForm(VaptchaForm):
    email = StringField(
        label='邮箱',
        description='邮箱',
        validators=[
            DataRequired('邮箱必填!'),
            Length(max=50, message='邮箱长度不能超过50个字符'),
            Email('邮箱格式错误'),

        ],
        render_kw={
            'lay-verify':'email',
            'lay-vertype':'tips',
            'placeholder':'请输入邮箱',
            'autocomplete':'off',
            'class':'layui-input'
        }
    )

    name = StringField(
        label='昵称',
        description='昵称',
        validators=[
            Length(max=22, message='昵称长度不能超过22个字符'),
            DataRequired('昵称必填'),
        ],
        render_kw={
            'lay-verify':'nickname',
            'lay-vertype':'tips',
            'placeholder':'请输入昵称',
            'autocomplete':'off',
            'class':'layui-input'
        }
    )

    comment = TextAreaField(
        label='评论内容',
        description='评论内容',
        validators=[
            DataRequired('评论内容必填!'),
            Length(max=250,message='评论内容最大长度250字符')
        ],
        render_kw={
            'lay-verify': 'comment',
            'lay-vertype': 'msg',
            'placeholder': '请输入内容',
            'class':'layui-textarea fly-editor',
        }
    )

    submit = SubmitField(
        '提交',
        render_kw={
            'class': 'layui-btn',
            'lay-filter':'*',
            'lay-submit':None
        }
    )

home/__init__.py
# coding:utf-8
from flask import Blueprint, request

from common.configs import VAPTCHA_ID
from common.extends import db

from common.models import Classify, Site, Post, Review, Tag
from common.util import site_to_dict

home = Blueprint('home', __name__)

def getHot(cid=None, num=10):
    '''
    浏览最多文章
    :param cid: 分类id, None代表查所有分类
    :param num: 取文章条数
    :return: 文章(Post对象)结果集
    '''
    # if cid:
    #     return Post.query.filter_by(cid=cid).order_by(Post.view.desc()).limit(num).all()
    return Post.query.order_by(Post.view.desc()).limit(num).all()


def getTag(cid=None, num=10):
    return Tag.query.order_by(Tag.click.desc()).limit(num).all()


def vaptcha(width=None, height=None):
    data = dict(
        id = VAPTCHA_ID,
        width = width+'px' if width else 'auto',
        height = height+'px' if height else 'auto',
    )
    return data


def getReviews(num=10):
    '''
    评论最多文章
    :param num: 取文章条数
    :return: 结果集
    '''
    sub = db.func.count(Review.pid)
    return db.session.query(Post.title, sub.label('rn'),Post.id).join(Review).group_by(Review.pid).order_by(sub.desc()).limit(num).all()


@home.context_processor
def common():
    # 导航
    nav = Classify.query.filter(Classify.asn < 1).order_by(Classify.sort).all()
    # 网站
    site = Site.query.filter_by(group='site').all()
    # 网站名字
    name = Site.query.filter_by(name='title').first()

    webname = name.value if name else '网站名称'

    data = dict(
        site=site_to_dict(site),
        nav=nav,
        webname=webname,
        hot=getHot,
        reviews=getReviews,
        wtag=getTag,
        vaptcha=vaptcha
    )
    return data

@home.before_request
def webs_witch():
    site = Site.query.filter(Site.name.in_(['switch','mark'])).all()
    site = site_to_dict(site)
    if request.path == '/login': return None
    if site['switch'] == '2': return site['mark']

from home import views

home/views.py
# coding:utf-8
import re
from flask import render_template, request, jsonify, g, flash, redirect, url_for, session

from common.extends import db
from common.models import Site, Post, Classify, Review, Tag
from common.util import site_to_dict
from home import home
from home.forms import ReviewForm, LoginForm
from home.weigets import Breadcrumb


@home.route('/')
def index():
    site = Site.query.filter_by(group='seo').all()
    page = request.args.get('page', 1, type=int)
    post = Post.getPagination(page, num=10)
    data = dict(breadcrumb=Breadcrumb().get(), gtop=Post.getTop(), main=site_to_dict(site), pagination=post)
    return render_template('home/index.html', **data)

@home.route('/<title>.c<int:id>.p<int:page>')
def classify(title, id, page):
    post = Post.getPagination(page, cid=id)
    main = Classify.query.get(id)
    gtop = Post.getTop(cid=id, num=3)
    args = dict(endpoint='home.classify', title=title, id=id)
    data = dict(pagination=post, gtop=gtop, breadcrumb=Breadcrumb(main).get(), args=args, main=main)
    return render_template('home/classify.html', **data)

@home.route('/<title>.p<int:id>.html', methods=['GET','POST'])
def post(title, id):
    form = ReviewForm()
    main = Post.query.get_or_404(id)

    g.view_post_passwd = ''
    if request.method == 'POST' and request.form.get('passwd2') != main.passwd:
        flash('查看密码不正确!', category='err')
    if request.form.get('passwd2') == main.passwd:
        g.view_post_passwd = main.passwd

    data = dict(main=main, breadcrumb=Breadcrumb(main).get(), form=form)
    Post.query.filter_by(id = id).update({"view": main.view + 1})
    db.session.commit()
    return render_template('home/post.html', **data)

@home.route('/post/reviews/<int:pid>', methods=['POST'])
def post_reviews(pid):
    status = 1  # 前台接收状态
    action = 'false' #前台跳转地址
    f = Post.query.get_or_404(pid)
    if f.is_review == 1: return jsonify(dict(status=1, msg={'comment':['此篇文章不充许评论']}, action=action))

    form = ReviewForm()
    comment = form.data.get('comment')

    pat = re.compile(r'(<a\shref="#at(\d+?)">@([a-zA-Z0-9_\u4e00-\u9fa5\s·]+?)</a>)')
    res = pat.findall(comment)
    ats = []

    comment = re.sub(pat,'',comment)
    comment = re.sub(r'&nbsp;[\s\n]*&nbsp;','',comment)

    for at in res:
        if Review.query.filter_by(name=at[2], id=at[1]).first(): ats.append(at[0])

    if form.validate_on_submit():
        if not comment.replace('&nbsp;','').strip():
            return '{"status":"1", "msg":{"comment":["评论内容不能为空!"]}, "action":"false"}'
        review = Review(
            name   = form.data.get('name').strip(),
            email  = form.data.get('email').strip(),
            comment= comment,
            at     = '&nbsp;'.join(list(set(ats))),
            pid    = pid
        )
        db.session.add(review)
        db.session.flush()
        action = review.id
        db.session.commit()
        status = 0

    data = dict(
        status = status,
        msg = form.errors,
        action = action
    )
    return jsonify(data)

@home.route('/<name>.t<int:id>')
def tag(name,id):
    main = Tag.query.get_or_404(id)
    main.title = main.name
    data = dict(main=main, gtop=Post.getTop(), breadcrumb=Breadcrumb(main).get())
    return render_template('home/tag.html', **data)

@home.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        obj = Site.query.filter(Site.name.in_(['username','password','nikename'])).all()
        user = site_to_dict(obj)
        if user['username'] == form.data.get('username') and user['password'] == form.data.get('password'):
            session['login'] = 1
            session['nikename'] = user['nikename']
            return redirect(url_for('admin.index'))
        else:
            flash('帐户或者密码不正确!', category='err')
            return redirect('/login')
    return render_template('/home/login.html',form=form)

templates/home/widgets/ad.html
{% macro ad(data) %}
<div class="fly-panel">
    <div class="fly-panel-title">
        广告区域
    </div>
    <div class="fly-panel-main">
        <a href="#" class="fly-zanzhu">虚席以待</a>
    </div>
</div>
{% endmacro %}

templates/home/widgets/gtop.html
{% macro gtop(data) %}
    {%if data%}
    <div class="fly-panel">
        <div class="fly-panel-title fly-filter"><a>置顶</a></div>
        <ul class="fly-list">
            {%for item in data%}
            <li>
                <h2 title="{{item.title}}">
                    <a href="{{url_for('home.classify',id=item.classify.id, title=item.classify.title, page=1)}}" class="layui-badge">{{item.classify.title}}</a>
                    <a href="{{url_for('home.post',id=item.id,title=item.title)}}">{{item.title}}</a>
                </h2>
                <div class="fly-list-info">
                    <span>{{item.uptime.strftime('%Y-%m-%d')}}</span>
                    <span class="fly-list-kiss layui-hide-xs" title="浏览次数"><i class="iconfont">&#xe60b;</i> {{item.view}}</span>
                    <span class="fly-list-nums"><i class="iconfont icon-pinglun1" title="评论数"></i> {{item.reviews|length}}</span>
                </div>
                <div class="fly-list-badge">
                    {%if item.passwd%}
                    <span title="密码查看" class="layui-badge">密码</span>
                    {%endif%}
                </div>
            </li>
            {%endfor%}
        </ul>
    </div>
    {%endif%}
{% endmacro %}

templates/home/widgets/hot.html
{% macro hot(data) %}

<dl class="fly-panel fly-list-one">
    <dt class="fly-panel-title">热门文章</dt>
    {%if data%}
    {%for item in data%}
    <dd>
        <a href="{{url_for('home.post',title=item.title,id=item.id)}}">{{item.title}}</a>
        <span><i class="iconfont">&#xe60b;</i> {{item.view}}</span>
    </dd>
    {%endfor%}
    {%else%}
    <!-- 无数据时 -->
    <div class="fly-none">没有相关数据</div>
    {%endif%}
</dl>

{% endmacro %}

templates/home/widgets/links.html
{% macro links(data) %}
<div class="fly-panel fly-link">
    <h3 class="fly-panel-title">友情链接</h3>
    <dl class="fly-panel-main">
        <dd><a href="http://www.layui.com/" target="_blank">layui</a><dd>
        <dd><a href="http://layim.layui.com/" target="_blank">WebIM</a><dd>
        <dd><a href="http://layer.layui.com/" target="_blank">layer</a><dd>
        <dd><a href="http://www.layui.com/laydate/" target="_blank">layDate</a><dd>
        <dd><a href="mailto:admin@skiss.cc?subject=申请友情链接" class="fly-link">申请友链</a><dd>
    </dl>
</div>
{% endmacro %}

templates/home/widgets/pagination.html
{% macro pagination(pagination,args) %}
<div class="layui-box layui-laypage layui-laypage-default">
    {%if pagination.has_prev %}
        <a href="{{url_for(page=pagination.prev_num,**args)}}" class="layui-laypage-prev">上一页</a>
    {% endif %}

    {% for foo in pagination.iter_pages(left_current=2,right_current=3) %}
        {% if foo %}
            {%if foo == pagination.page %}
            <span class="layui-laypage-curr"><em class="layui-laypage-em"></em><em>{{foo}}</em></span>
            {% else %}
            <a href="{{url_for(page=foo,**args)}}">{{foo}}</a>
            {%endif%}
        {% else %}
            <span class="layui-laypage-spr">…</span>
        {% endif %}
    {% endfor %}

    {%if pagination.has_next %}
        <a href="{{url_for(page=pagination.next_num,**args)}}" class="layui-laypage-next">下一页</a>
    {% endif %}
</div>
{% endmacro %}

templates/home/widgets/reviews.html
{% macro reviews(data) %}
<dl class="fly-panel fly-list-one">
    <dt class="fly-panel-title">热评文章</dt>
    {%if data%}
    {%for item in data%}
    <dd>
        <a href="{{url_for('home.post',title=item.title,id=item.id)}}">{{item.title}}</a>
        <span><i class="iconfont icon-pinglun1"></i> {{item.rn}}</span>
    </dd>
    {%endfor%}
    {%else%}
    <!-- 无数据时 -->
    <div class="fly-none">没有相关数据</div>
    {%endif%}
</dl>
{% endmacro %}

templates/home/widgets/tag.w.html
{% macro wtag(data) %}
<div class="fly-panel">
    <h3 class="fly-panel-title">TAG标签</h3>
    {%if data%}
    <div class="fly-panel-main zb-tags">
        {%for item in data%}
        <a href="{{url_for('home.tag',name=item.name,id=item.id)}}" class="layui-badge layui-bg-green">{{item.name}}</a>
        {%endfor%}
    </div>
    {%else%}
    <!-- 无数据时 -->
    <div class="fly-none">没有相关数据</div>
    {%endif%}
</div>
{% endmacro %}

templates/home/widgets/vaptcha.html
{% macro vaptcha(vaptcha) %}
<div data-vid="{{vaptcha.id}}">
    <div class="vaptcha-init-main">
        <div class="vaptcha-init-loading">
            <a href="https://www.vaptcha.com" target="_blank">
                <img src="https://cdn.vaptcha.com/vaptcha-loading.gif" />
            </a>
            <span class="vaptcha-text">Vaptcha启动中...</span>
        </div>
    </div>
</div>
{% endmacro %}